export enum OrderStatus {
  IN_PREPARATION = 'IN_PREPARATION',
  CANCELED = 'CANCELED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  CONFIRMED = 'CONFIRMED',
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
}
